apiVersion: v1
kind: BuildConfig
metadata:
  name: nextplyspa
  labels:
    app: php56
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php56", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret:  dcddc8cd95c0ed61edb4628a6a87c99557931d82
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'php56', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'php56')
           }
         }
